#!/bin/bash

command_exists() {
	command -v "$@" > /dev/null 2>&1
}

if command_exists docker; then
  version=$(docker -v)
  echo "Docker already installed, using $version"
else
  echo "Installing Docker..."
  bash <(curl -fsSL get.docker.com)
  sudo usermod -aG docker $(whoami)
fi

system=$(uname -s | tr A-Z a-z)
machine=$(uname -m)
if [ $machine == "x86_64" ]; then
  machine="amd64"
else
  machine="386"
fi

echo "Installing MESG..."
link=$(curl -s https://api.github.com/repos/mesg-foundation/core/releases/latest | grep "browser_download_url.*$system.*$machine" | cut -d : -f 2,3 | tr -d \")

path="/usr/local/bin/mesg-core"

sudo curl --progress -L $link -o $path
sudo chmod +x $path

$path start